language: node_js
node_js:
  - "6"

notifications:
  email: false

cache:
  directories:
    - node_modules

install:
  - npm install
  - npm install -g firebase-tools

script:
  - npm run test
  - npm run build-dev
  - npm run build-prod
