language: node_js
node_js:
  - "6"

notifications:
  email: false
  webhooks:
    urls:
      - https://www.vivifyscrum.com/ciintegrations/travis/859a04cae9cfad158280e9fc4ca8a9a5

cache:
  directories:
    - node_modules

install:
  - npm install
  - npm install -g firebase-tools

script:
  - npm run test
  - npm run build-dev
  - npm run build-prod

after_success:
  - test $TRAVIS_BRANCH = "master" && firebase use default
  - test $TRAVIS_BRANCH = "master" && firebase use dev
  - firebase deploy --token $FIREBASE_TOKEN
